def init():
    global TIMESTAMP_GRANULARITY
    global LOCATION_PRECISION
    global HEATMAP_SELECTED
    global ILLUMINOCITY_SELECTED
    global HUMIDITY_SELECTED
    global USERS_TRACKING_SELECTED
    global MIN_X
    global MAX_X
    global MIN_Y
    global MAX_Y
    global HUMIDITY_INITIALIZED

    global DEVICES_COORDINATES

    TIMESTAMP_GRANULARITY = 5
    LOCATION_PRECISION = 50

    HUMIDITY_INITIALIZED = False

    MIN_X = MAX_X = MIN_Y = MAX_Y = 0

    DEVICES_COORDINATES = [
        [200, 100], [300, 600], [300, 400], [550, 300], [820, 300], [1000, 600], [620, 620]
    ]